# Generated by Django 2.1.2 on 2019-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'tb_access_group',
            },
        ),
        migrations.CreateModel(
            name='DataPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('endpoint', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'tb_data_permission',
            },
        ),
        migrations.AddField(
            model_name='accessgroup',
            name='permissions',
            field=models.ManyToManyField(to='toolbox.DataPermission'),
        ),
    ]
