# Generated by Django 2.1.2 on 2019-09-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapermission',
            name='code',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
