# Generated by Django 2.1.2 on 2019-09-04 08:26

from django.db import migrations


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.create(
        name='Asset',
        endpoint='/asset/',
        method='GET',
        code='MOD_ASSETS'
    )

    data_permission.objects.create(
        name='Notification',
        endpoint='/notifications/notifications/',
        method='GET',
        code='MOD_NOTIFICATIONS'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0002_datapermission_code'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
