# Generated by Django 2.1.2 on 2019-09-25 09:32

from django.db import migrations

from toolbox.constants import DATA_TRANSACTIONS, DATA_STATUS


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_STATUS,
        defaults=dict(
            name='Status',
            endpoint='/status-details/',
            method='GET',
            query_fields=[
            ]
        )
    )

    data_permission.objects.update_or_create(
        code=DATA_TRANSACTIONS,
        defaults=dict(
            name='Transaction',
            endpoint='/transactions/',
            method='GET',
            query_fields=[
                'user_id',
                'type',
                'start_date',
                'end_date',
            ]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0009_remove_accessgroup_environment_setting'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
