# Generated by Django 2.1.2 on 2019-10-01 13:45

from django.db import migrations

from toolbox.constants import DATA_NOTIFICATION_TYPES


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_NOTIFICATION_TYPES,
        defaults=dict(
            name='Notification type',
            endpoint='/notifications/types/',
            method='GET',
            query_fields=[
            ]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0010_create_status_and_transactions_data_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
