# Generated by Django 2.1.2 on 2019-10-18 14:21

from django.db import migrations

from toolbox.constants import DATA_NOTIFICATION_EVENTS, DATA_NOTIFICATION_EVENT


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_NOTIFICATION_EVENTS,
        defaults=dict(
            name='Notification events',
            endpoint='/notifications/events/',
            method='GET',
            query_fields=[
                'type_id',
                'start_date',
                'end_date'
            ]
        )
    )

    data_permission.objects.update_or_create(
        code=DATA_NOTIFICATION_EVENT,
        defaults=dict(
            name='Notification event',
            endpoint='/notifications/event/',
            method='GET',
            query_fields=[
                'notification_id'
            ]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0011_create_notification_types__data_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
