# Generated by Django 2.1.2 on 2019-10-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0012_create_notification_events_data_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgroup',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='datapermission',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='datapermission',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
