# Generated by Django 2.1.2 on 2019-11-07 08:07

from django.db import migrations

from toolbox.constants import DATA_PORTFOLIO_HISTORY


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_PORTFOLIO_HISTORY,
        defaults=dict(
            name='Portfolio history',
            endpoint='/portfolio/history/',
            method='GET',
            query_fields=[
                'start_date',
                'end_date',
                'user',
            ]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0015_create_portfolio_performance_data_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
