# Generated by Django 2.1.2 on 2019-11-22 09:47

from django.db import migrations

from toolbox.constants import DATA_RECURRENT_ORDERS


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_RECURRENT_ORDERS,
        defaults=dict(
            name='Recurrent order',
            endpoint='/asset/recurrent_orders',
            method='GET',
            query_fields=[
                'user',
                'direct_debit'
            ]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0017_create_goals_data_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
