# Generated by Django 2.1.2 on 2019-12-16 14:54

from django.db import migrations

from toolbox.constants import DATA_INTERNAL_REPORTS_GENERATE_GOALS, \
    DATA_INTERNAL_REPORTS_GENERATE_USERS_RISK_SCORE_LIST


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_INTERNAL_REPORTS_GENERATE_GOALS,
        defaults=dict(
            name='Internal reports generate goals',
            endpoint='/internal-reports/generate/goals/',
            method='GET',
            query_fields=[
                'start_date',
                'end_date'
            ]
        )
    )

    data_permission.objects.update_or_create(
        code=DATA_INTERNAL_REPORTS_GENERATE_USERS_RISK_SCORE_LIST,
        defaults=dict(
            name='Internal reports generate users risk score list',
            endpoint='/internal-reports/generate/users-risk-score-list/',
            method='GET',
            query_fields=[
                'upper_risk_score',
                'lower_risk_score'
            ]
        )
    )

class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0019_create_frequency_types_data_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
