# Generated by Django 2.1.2 on 2019-12-24 10:12

from django.db import migrations

from toolbox.constants import (
    DATA_INTERNAL_REPORTS_GENERATE_BALANCES,
    DATA_INTERNAL_REPORTS_GENERATE_ORDERS,
    DATA_INTERNAL_REPORTS_GENERATE_RECURRENT_ORDERS)


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_INTERNAL_REPORTS_GENERATE_BALANCES,
        defaults=dict(
            name='Internal reports generate balances',
            endpoint='/internal-reports/generate/balances/',
            method='GET',
            query_fields=[]
        )
    )

    data_permission.objects.update_or_create(
        code=DATA_INTERNAL_REPORTS_GENERATE_ORDERS,
        defaults=dict(
            name='Internal reports generate orders',
            endpoint='/internal-reports/generate/orders/',
            method='GET',
            query_fields=[
                'start_date',
                'end_date'
            ]
        )
    )

    data_permission.objects.update_or_create(
        code=DATA_INTERNAL_REPORTS_GENERATE_RECURRENT_ORDERS,
        defaults=dict(
            name='Internal reports generate recurrent orders',
            endpoint='/internal-reports/generate/recurrent-orders/',
            method='GET',
            query_fields=[
                'start_date',
                'end_date',
                'direct_debit',
                'period_finished'
            ]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0020_change_data_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
