# Generated by Django 2.1.2 on 2020-02-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0021_create_internal_reports_data_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgroup',
            name='date_format_template',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
