# Generated by Django 2.1.2 on 2020-03-01 19:21

from django.db import migrations

from toolbox.constants import DATA_TRANSACTION_TYPES


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_TRANSACTION_TYPES,
        defaults=dict(
            name='Transaction types',
            endpoint='/transactions/types/',
            method='GET',
            query_fields=[]
        )
    )

class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0022_accessgroup_date_format_template'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
