# Generated by Django 2.1.2 on 2020-03-06 15:41

from django.db import migrations

from toolbox.constants import DATA_QUESTIONNAIRE


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_QUESTIONNAIRE,
        defaults=dict(
            name='Questionnaire',
            endpoint='/risk-profile/questionnaire/',
            method='GET',
            query_fields=[
                'version',
                'user',
            ]
        )
    )

class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0023_create_transactions_types_data_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
