# Generated by Django 2.1.2 on 2020-03-10 14:26

from django.db import migrations

from toolbox.constants import (
    DATA_RISK_SCORE_SUGGESTED,
    DATA_RISK_SCORE_SELECTED
)


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_RISK_SCORE_SUGGESTED,
        defaults=dict(
            name='Risk score suggested',
            endpoint='/risk-profile/risk-profile/',
            method='GET',
            query_fields=[
                'version',
                'user',
            ]
        )
    )

    data_permission.objects.update_or_create(
        code=DATA_RISK_SCORE_SELECTED,
        defaults=dict(
            name='Risk score selected',
            endpoint='/risk-profile/',
            method='GET',
            query_fields=[
                'user',
            ]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0024_create_questionnaire_data_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
