# Generated by Django 2.1.2 on 2020-03-12 15:33

from django.db import migrations

from toolbox.constants import DATA_INTERNAL_REPORTS_GENERATE_ASSETS_LIST


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_INTERNAL_REPORTS_GENERATE_ASSETS_LIST,
        defaults=dict(
            name='Internal reports generate assets list',
            endpoint='/internal-reports/generate/assets-list/',
            method='GET',
            query_fields=[]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0025_create_risk_profile_data_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
