# Generated by Django 2.1.2 on 2020-03-23 10:04

from django.db import migrations

from toolbox.constants import DATA_ASSETS_SNAPSHOT


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_ASSETS_SNAPSHOT,
        defaults=dict(
            name='Assets snapshots',
            endpoint='/asset/assets-snapshots/',
            method='GET',
            query_fields=[]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0026_create_assets_internal_report_data_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
