# Generated by Django 2.1.2 on 2020-03-27 07:27

from django.db import migrations

from toolbox.constants import DATA_ASSETS_SNAPSHOT, DATA_GOALS_SNAPSHOT


def create_data_permissions(apps, schema_editor):
    data_permission = apps.get_model("toolbox", "DataPermission")

    data_permission.objects.update_or_create(
        code=DATA_GOALS_SNAPSHOT,
        defaults=dict(
            name='Goals snapshots',
            endpoint='/analytics/snapshot/goals/',
            method='GET',
            query_fields=[]
        )
    )

    data_permission.objects.update_or_create(
        code=DATA_ASSETS_SNAPSHOT,
        defaults=dict(
            name='Assets snapshots',
            endpoint='/analytics/snapshot/assets/',
            method='GET',
            query_fields=[]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0027_create_assets_snapshot_data_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_data_permissions, migrations.RunPython.noop
        )
    ]
